// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";

// Only these emails are allowed admin access
const ADMIN_EMAILS = ["noureldein1100@gmail.com", "noureldein1100@outlook.com", "noureldein1100@hotmail.com"];

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const FIREBASE_API_KEY =
      process.env.FIREBASE_API_KEY || "AIzaSyBBv2wD-6C8gWAylPsuxp4VtAn4urWfSIo";

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: No valid authorization header");
    }

    const token = authHeader.replace("Bearer ", "").trim();
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    // Verify Firebase token via Google Identity Toolkit
    const res = await fetch(
      `https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${FIREBASE_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ idToken: token }),
      },
    );
    const data = await res.json();
    if (!res.ok || !data.users?.[0]) {
      throw new Error("Unauthorized: Invalid or expired token");
    }

    const firebaseUser = data.users[0];
    const userEmail: string = (firebaseUser.email ?? "").toLowerCase();
    const userId: string = firebaseUser.localId;

    // Restrict to the allowed admin account(s)
    const isAdmin =
      ADMIN_EMAILS.some((e) => userEmail === e.toLowerCase()) ||
      userEmail.startsWith("noureldein1100");

    if (!isAdmin) {
      throw new Error("Forbidden: This account does not have admin access");
    }

    return next({
      context: {
        userId,
        userEmail,
      },
    });
  },
);
